---
ID: d05f7f42-0c30-4178-bfd8-db4eced72855
Parent: 37cd3bd2-de15-4eab-9b1b-c04c6aba8907
Template: 0437fee2-44c9-46a6-abe9-28858d9fee8c
Path: /sitecore/templates/Project/OscarMayer/Parameters
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20160204T215640Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
